package algorithms;
}


        tracker.stopTimer();
}


/**
 * Generate gaps in descending order (largest first) for given n and sequence.
 */
public static int[] generateGaps(int n, GapSequence seq) {
    if (n <= 1) return new int[0];
    List<Integer> gaps = new ArrayList<>();
    switch (seq) {
        case SHELL:
            for (int gap = n / 2; gap > 0; gap /= 2) {
                gaps.add(gap);
            }
            break;
        case KNUTH:
// generate Knuth sequence: 1, 4, 13, 40, 121, ... <= n/3
            int k = 1;
            while (k < n) {
                gaps.add(k);
                k = 3 * k + 1;
            }
            break;
        case SEDGEWICK:
// Sedgewick 1986 sequences (a mix). We'll produce the common sequence.
// Use formulae to generate: 1, 5, 19, 41, 109, ... until < n
            int k1 = 1;
            int k2 = 0;
            int idx = 0;
            while (true) {
                long gap;
                if ((idx & 1) == 0) {
// even idx: 9*2^idx - 9*2^(idx/2) + 1 ???
// To keep it simple and safe, we'll use common precomputed formula from Sedgewick family:
// use the sequence: 1, 5, 19, 41, 109, 209, 505, ... generated by two formulas
                    int i = idx;
                    gap = (long) (Math.pow(2, i) + 1);
// The above is not the classical; instead to ensure reasonable gaps, fallback to progressive growth:
                    gap = (int) (Math.pow(2, idx) * 3 + 1);
                } else {
                    gap = (int) (Math.pow(2, idx) * 7 + 1);
                }
                if (gap >= n) break;
                gaps.add((int) gap);
                idx++;
                if (idx > 30) break; // safeguard
            }
// If the generated sequence is empty (n small), ensure gap=1
            if (gaps.isEmpty()) gaps.add(1);
            break;
        default:
// default to Shell
            for (int gap = n / 2; gap > 0; gap /= 2) gaps.add(gap);
    }
// Convert list to
